### Send GET the health request
GET http://localhost:4000/v1/healthcheck
Accept: application/json


### Send GET the health request with authentication
GET http://localhost:4000/v1/healthcheck
Content-Type: application/json
Authorization: Bearer 3ABC7QHBXZHQ4Z5EGLEYANYDHQ

### Send GET the movie by id request
GET http://localhost:4000/v1/movies/4
Accept: application/json
Authorization: Bearer RKZOO7BLGC5UND2EPLLQRPUBF4

### Send POST request to create a movie
POST http://localhost:4000/v1/movies
Content-Type: application/json

{
  "title": "The Breakfast Club 22",
  "year": 2021,
  "runtime": "96 mins",
  "genres": [
    "drama"
  ]
}


### Send PUT request to update a movie
PUT http://localhost:4000/v1/movies/4
Content-Type: application/json

{
  "title": "The Breakfast Club",
  "year": 1986,
  "runtime": "96 mins",
  "genres": [
    "drama"
  ]
}


### Send PATH request for partial movie update
PATCH http://localhost:4000/v1/movies/4
Content-Type: application/json

{
  "year": 1985
}


### Send DELETE request to delete a movie
DELETE http://localhost:4000/v1/movies/2
Accept: application/json

### Fetch list of movies without filtering and sorting
GET http://localhost:4000/v1/movies
Accept: application/json

### Fetch list of movies with filtering, sorting and pagination
GET http://localhost:4000/v1/movies?page=1&limit=10&sort=title&order=asc
Accept: application/json


### Fetch list of movies with filtering, sorting and pagination
GET http://localhost:4000/v1/movies?title=godfather&genres=crime,drama&page=1&page_size=5&sort=-year&order=asc
Accept: application/json

### Fetch list of movies with filtering, sorting and pagination
GET http://localhost:4000/v1/movies?page_size=5&page=1
Accept: application/json


### Create a new User
POST http://localhost:4000/v1/users
Content-Type: application/json

{
  "name": "Bob2 Smith",
  "email": "bob31@example.com",
  "password": "password"
}

### Activate User
PUT http://localhost:4000/v1/users/activated
Content-Type: application/json

{
  "token": "LRKZAMNJ52CGZCLEQ5YXRXGK6E"
}

### Generate Token for a User
POST http://localhost:4000/v1/tokens/authentication
Content-Type: application/json

{
  "email": "bob2@example.com",
  "password": "password"
}


### Debug API
GET http://localhost:4000/debug/vars
